---
- name: Install Docker and Docker Compose
  hosts: localhost
  become: yes  # Run tasks with elevated privileges (sudo)

  tasks:
    - name: Install dependencies
      package:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
      when: ansible_distribution == 'Ubuntu'

    - name: Install Docker
      package:
        name: docker-ce
        state: present
      when: ansible_distribution == 'Ubuntu'

    - name: Install Docker Compose
      command: >
        curl -sSL https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{ "linux" if ansible_architecture == "x86_64" else "arm64" }} -o /usr/local/bin/docker-compose
      args:
        creates: /usr/local/bin/docker-compose
      register: docker_compose_download

    - name: Set execute permissions for Docker Compose
      file:
        path: /usr/local/bin/docker-compose
        mode: 'a+x'
      when: docker_compose_download.changed

    - name: Display Docker version
      command: docker --version

    - name: Display Docker Compose version
      command: docker-compose --version


